# Generated by Django 3.0.8 on 2021-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germanText', models.CharField(max_length=50)),
                ('turkishText', models.CharField(max_length=50)),
                ('artikel', models.CharField(max_length=5)),
                ('plural', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germanText', models.CharField(max_length=100)),
                ('turkishText', models.CharField(max_length=100)),
                ('pastTense', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
